### ISSUE TITLE
Ability to remove words from the list.

### ISSUE THREAD

**Issue by shreyas-a** [shreyas-a/wordly#5]

**Comment by colbyguan** [comment]
@shreyas-a  I'm interested in working on this! I'm thinking of the UI changes to be as simple as adding a trash can icon to the right side of each row, and binding a click event to that.

**Comment by shreyas-a** [comment]
@colbyguan sure you can start working on it. If you need anything, ping me anytime.

**Comment by azharakbar** [comment]
Hi,
i am interested to work with this
Can u give more explanation .. like in which file .. and more abt the feature u expect ??

**Comment by shreyas-a** [comment]
@colbyguan are you working on the issue, if not, @azharakbar can start working on it

**Comment by colbyguan** [comment]
Almost done with the implementation, just need to finish message passing logic.
